version: '3.8'
services:
    build:
    restart: always
    ports:
      - 8080:8080
    environment:
    healthcheck:
      test: "exit 0"
    depends_on:

#    volumes:
#      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"